refresh_rate: 60 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S%.3fZ)(utc)} {l} {t} - {m}{n}"

  file:
    kind: rolling_file
    path: /var/log/qviewng/app.log
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S%.3fZ)(utc)} {l} {t} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 50 mb
      roller:
        kind: fixed_window
        pattern: /var/log/qviewng/app.{}.log
        base: 1
        count: 5

root:
  level: info
  appenders:
    - stdout
    - file
