#!/bin/sh
#
# This file contains the code that will run QView in beta and or production mode.
#
# The current vision is to have two environments active on the web (beta and production).
# All development environments would be on developer or tester laptops.
# Beta would be used for testing activiites and trying out new designs, new code, etc.
#
#
# Generally to run this you use the following command line.
#
# user@host:~/projects/qview$ nohup ./betarun &
#

# This line has been commented out (4/15/2026) by Collyn Brenner until further notice.
# export $(cat .env_beta | xargs) && cargo run --release >output
