ALTER TABLE tournaments ADD COLUMN address_line_1 VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE tournaments ADD COLUMN address_line_2 VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE tournaments ADD COLUMN state VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE tournaments ADD COLUMN zip_code VARCHAR(16) NOT NULL DEFAULT '';
