import dayjs, { Dayjs } from "dayjs";

/**
 * This is the TournamentChangeset type generated by _tsync_, but with the `fromdate` and `todate` types replaced.
 */
export interface TournamentChangesetTS extends Omit<TournamentChangeset, "fromdate" | "todate"> {
  fromdate: Dayjs | null;
  todate: Dayjs | null;
}

/**
 * This is the Tournament type generated by _tsync_, but with the `fromdate` and `todate` types replaced.
 */
export interface TournamentTS extends Omit<Tournament, "fromdate" | "todate" | "tid"> {
  tid: string;
  fromdate: Dayjs | null;
  todate: Dayjs | null;
}

export interface TournamentCreateUpdateResult {
  code: number;
  message: string;
  data: TournamentTS;
}

export interface PagedTournaments {
  count: number;
  items: TournamentTS[];
}

/** Return a `TournamentTS` created from the given `Tournament`. */
const dateStringToDayjs = (tournament: Tournament): TournamentTS => {
  const { fromdate, todate, tid, ...rest } = tournament;
  return {
    ...rest,
    tid: String(tid),
    fromdate: dayjs(fromdate),
    todate: dayjs(todate),
  };
};

export const TournamentAPI = {
  get: async (page: number, size: string): Promise<PagedTournaments> => {
    const response = await fetch(`/api/tournaments?page=${page}&page_size=${size}`);
    const result = await response.json();
    return {
      count: result.count,
      items: result.items.map((tournament: Tournament) => dateStringToDayjs(tournament)),
    };
  },
  getByDate: async (fromDate: number, toDate: number): Promise<TournamentTS[]> => {
    const response = await fetch(`/api/tournaments/filter?from_date=${fromDate}&to_date=${toDate}`);
    const result = await response.json();
    return result.map((tournament: Tournament) => dateStringToDayjs(tournament));
  },
  getById: async (tid: string): Promise<TournamentTS> => {
    const response = await fetch(`/api/tournaments/${tid}`);
    if (!response.ok) {
      if (response.status === 404) {
        throw new Error('Tournament not found');
      }
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const result = await response.json();
    return dateStringToDayjs(result);
  },
  create: async (tournament: TournamentChangesetTS, accessToken?: string): Promise<TournamentCreateUpdateResult> => {
    let nquery = JSON.stringify(tournament);
    let response = await fetch('/api/tournaments', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(accessToken ? { 'Authorization': `Bearer ${accessToken}` } : {}),
        },
        body: nquery,
      });
      if (response.status === 401) {
        throw new Error("401");
      }
      const result = await response.json();
      console.log(result);
      const { data, ...rest } = result;
      return {
        ...rest,
        data: dateStringToDayjs(result.data)
      };
    },
  delete: async (id: string) =>
    await fetch(`/api/tournaments/${id}`, { method: 'DELETE' }),
  update: async (id: string, tournament: TournamentChangesetTS, accessToken?: string): Promise<TournamentCreateUpdateResult> => {
    const response = await fetch(`/api/tournaments/${id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        ...(accessToken ? { 'Authorization': `Bearer ${accessToken}` } : {}),
      },
      body: JSON.stringify(tournament),
    });
    console.log({ response });
    if (response.status === 401) {
      throw new Error("401");
    }
    const result = await response.json();
    console.log({ result });
    const { data, ...rest } = result;
    return {
      ...rest,
      data: dateStringToDayjs(result.data)
    };
  }
}
